name: flutter_img
description: Just another flutter image widget that can handel asset and network png,jpg and svg
version: 0.0.3
homepage: https://github.com/ishafiul/flutter_img
repository: https://github.com/ishafiul/flutter_img

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.7.0
  flutter_cache_manager: ^3.3.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
