name: flutter_img
description: Just another flutter image widget that can handel asset and network png,jpg and svg
version: 0.1.6+148
homepage: https://github.com/ishafiul/flutter_img
repository: https://github.com/ishafiul/flutter_img

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=2.8.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blurhash: ">=0.7.0 <0.9.0"
  flutter_cache_manager: ^3.3.0
  flutter_svg: ^2.0.7
  http: ^1.1.0
  mime: ^1.0.4

cider:
  link_template:
    tag: https://github.com/The-Artista/flutter_img/releases/tag/v0.1.6 # initial release link template
    diff: https://github.com/The-Artista/flutter_img/compare/v0.1.5...v0.1.6 # subsequent releases link template

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ">=0.3.0 <2.0.0"
  very_good_analysis: ">=5.0.0 <7.0.0"
  cider: ^0.2.3
