name: flutter_img
description: Just another flutter image widget that can handel asset and network png,jpg and svg
version: 0.1.4
homepage: https://github.com/ishafiul/flutter_img
repository: https://github.com/ishafiul/flutter_img

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.7.0
  flutter_cache_manager: ^3.3.0
  flutter_svg: ^2.0.7
  http: ^1.1.0
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ">=0.3.0 <2.0.0"
  very_good_analysis: ^5.0.0
