name: 🚀 Publish New version
on:
  push:
    branches:
      - main

env:
  JAVA_VERSION: "18.x"
  FLUTTER_VERSION: "3.13.0"
  FLUTTER_CHANNEL: "stable"

jobs:
  update_code_version:
    name: 🚀 Publish New version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.1.0
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - name: 🔧 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{inputs.flutter_version}}
          channel: ${{inputs.flutter_channel}}
          cache: true

      - name: 🔖 Generating new version and change log
        run: |
          flutter pub global activate cider
          cider version ${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}+${{ env.NUMBER_OF_COMMITS }}
      - name: Get changelog
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITOKEN }}
          exclude_types: other,doc,chore

      - name: Print tag description
        run: |
          cider log changed "${{ steps.changelog.outputs.changes }}"
          cider release

