name: 🚀 Publish New version
on:
  push:
    tags:
      - "*"

env:
  JAVA_VERSION: "18.x"
  FLUTTER_VERSION: "3.13.0"
  FLUTTER_CHANNEL: "stable"

jobs:
  update_code_version:
    name: 🚀 Publish New version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - name: 🔧 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{inputs.flutter_version}}
          channel: ${{inputs.flutter_channel}}
          cache: true

      - name: 🔖 Generating new version and change log
        run: |
          flutter pub global activate cider
          cider release
          cider version ${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}+${{ env.NUMBER_OF_COMMITS }}
      - name: 🔀 Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          # Change it to your own branch
          branch: main
          message: "Update version on pubspec.yaml & update change log"
          # Change it to your own branch
          push: origin main --force


      - name: 🔐 Setup Pub Credentials
        run: |
          mkdir -p $HOME/.config/dart
          cat <<EOF > $HOME/.config/dart/pub-credentials.json
          {
            "accessToken": "${{ secrets.PUB_CREDS_ACCESS_TOKEN }}",
            "refreshToken": "${{ secrets.PUB_CREDS_REFRESH_TOKEN }}",
            "idToken": "${{ secrets.PUB_CREDS_ID_TOKEN }}",
            "tokenEndpoint": "https://accounts.google.com/o/oauth2/token",
            "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
            "expiration": ${{ secrets.PUB_CREDS_EXPIRATION }}
          }

      - name: 📢 Publish
        run: flutter pub publish -f