name: Updating_Code_Version
on:
  push:
    tags:
      - "*"

env:
  JAVA_VERSION: "18.x"
  FLUTTER_VERSION: "3.13.0"
  FLUTTER_CHANNEL: "stable"

jobs:
  update_code_version:
    name: Updating the code version and commiting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: |
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          pub global activate cider
          cider release
          cider version ${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}+${{ env.NUMBER_OF_COMMITS }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          # Change it to your own branch
          branch: main
          message: "Update version on pubspec.yaml & update change log"
          # Change it to your own branch
          push: origin main --force